<a href="https://colab.research.google.com/github/desaivaibhav95/Natural-Language-Processing-NLP-and-Web-Scraping/blob/master/Movie_Review_dataset_analysis_(Bag_of_Words_and_TF_IDF)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Movie Review dataset consists of two columns class and text. The text column consists of reviews and the class column consists the information of whether the review is positive or negative.

In [1]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/NLP Training/movie-Review dataset.csv')

In [2]:
df.head()

class                                               text
0   Pos   films adapted from comic books have had plent...
1   Pos   every now and then a movie comes along from a...
2   Pos   you ve got mail works alot better than it des...
3   Pos      jaws   is a rare film that grabs your atte...
4   Pos   moviemaking is a lot like being the general m...

In [3]:
import numpy as np
np.random.seed(500)

In [4]:
# Remove number
import re # import all regular expressions
df['text'] = [re.sub('\d','', i) for i in df['text']]
df.head()

class                                               text
0   Pos   films adapted from comic books have had plent...
1   Pos   every now and then a movie comes along from a...
2   Pos   you ve got mail works alot better than it des...
3   Pos      jaws   is a rare film that grabs your atte...
4   Pos   moviemaking is a lot like being the general m...

In [5]:
# Replace punctuations with white space
import string
df['text'] = [re.sub('[%s]' % re.escape(string.punctuation), '', i) for i in df['text']]
df.head(10)

class                                               text
0   Pos   films adapted from comic books have had plent...
1   Pos   every now and then a movie comes along from a...
2   Pos   you ve got mail works alot better than it des...
3   Pos      jaws   is a rare film that grabs your atte...
4   Pos   moviemaking is a lot like being the general m...
5   Pos   on june       a self taught   idealistic   ye...
6   Pos   apparently   director tony kaye had a major b...
7   Pos   one of my colleagues was surprised when i tol...
8   Pos   after bloody clashes and independence won   l...
9   Pos   the american action film has been slowly drow...

In [6]:
# Convert all uppercase letters in the text to lowercase
df['text'] = [i.lower() for i in df['text']] 

## Tokenization

In [7]:
import pandas as pd
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
df['text_wt'] = [word_tokenize(i) for i in df['text']]
df.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


class  ...                                            text_wt
0   Pos  ...  [films, adapted, from, comic, books, have, had...
1   Pos  ...  [every, now, and, then, a, movie, comes, along...
2   Pos  ...  [you, ve, got, mail, works, alot, better, than...
3   Pos  ...  [jaws, is, a, rare, film, that, grabs, your, a...
4   Pos  ...  [moviemaking, is, a, lot, like, being, the, ge...

[5 rows x 3 columns]

In [8]:
# To show the stop words
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
stop_words # Show stop words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [9]:
# Remove all stop words
df['text_SW'] = [[i for i in j if not i in stop_words] for j in df['text_wt']] # remove the word which is available
# in stopword library
df.head()

class  ...                                            text_SW
0   Pos  ...  [films, adapted, comic, books, plenty, success...
1   Pos  ...  [every, movie, comes, along, suspect, studio, ...
2   Pos  ...  [got, mail, works, alot, better, deserves, ord...
3   Pos  ...  [jaws, rare, film, grabs, attention, shows, si...
4   Pos  ...  [moviemaking, lot, like, general, manager, nfl...

[5 rows x 4 columns]

## Lemmatization

In [10]:
nltk.download('tagsets')
# nltk.help.upenn_tagset()# tagset documentation
nltk.download('wordnet')

from collections import defaultdict #Default Dictionary is imported from collections
from nltk.corpus import wordnet as wn #the corpus reader wordnet is imported.
from nltk.tag import pos_tag
# WordNetLemmatizer requires Pos tags to understand if the word is noun or verb or adjective etc. 
#By default it is set to Noun
tag_map = defaultdict(lambda : wn.NOUN) #Dictionary is created where pos_tag (first letter) are the key values 
tag_map['J'] = wn.ADJ                   #whose values are mapped with the value 
tag_map['V'] = wn.VERB                  #from wordnet dictionary. We have taken the only first letter as 
tag_map['R'] = wn.ADV
# we will use it later in the loop.

tag_map

[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


defaultdict(<function __main__.<lambda>>, {'J': 'a', 'R': 'r', 'V': 'v'})

In [11]:
nltk.download('averaged_perceptron_tagger')

# Lemmatization
from nltk.stem import WordNetLemmatizer

# Initializing WordNetLemmatizer()
lemmatizer = WordNetLemmatizer()

df['lemma'] = [[lemmatizer.lemmatize(word, tag_map[tag[0]]) for word, tag in pos_tag(i)] for i in df['text_SW']]
df.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


class  ...                                              lemma
0   Pos  ...  [film, adapt, comic, book, plenty, success, wh...
1   Pos  ...  [every, movie, come, along, suspect, studio, e...
2   Pos  ...  [get, mail, work, alot, good, deserves, order,...
3   Pos  ...  [jaw, rare, film, grab, attention, show, singl...
4   Pos  ...  [moviemaking, lot, like, general, manager, nfl...

[5 rows x 5 columns]

We can observe in the above dataframe, how our text data has been transformed after applying operations like tokenization, stop words removal, Part of Speech tagging and lemmatization. 

In [12]:
# Joining all the words in the list of words after applying lemmatization operation

df['lemma2'] = df['lemma'].apply(lambda x: ' '.join(x))
df['lemma2'].head()

0    film adapt comic book plenty success whether s...
1    every movie come along suspect studio every in...
2    get mail work alot good deserves order make fi...
3    jaw rare film grab attention show single image...
4    moviemaking lot like general manager nfl team ...
Name: lemma2, dtype: object

## Word Embedding using Bag of Words (BOW)


In [13]:
# Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

# instantiate CountVectorizer()
# CountVectorizer to count the number of words (term frequency)
cv = CountVectorizer(max_features = 5000)

#this steps generates word counts for the words in your docs and return term-document matrix.
BOW = cv.fit_transform(df['lemma2']).toarray()

In [14]:
pd.DataFrame(BOW, columns=cv.get_feature_names()).head()

aaron  abandon  ability  able  aboard  ...  zeta  zombie  zone  zoom  zwick
0      0        0        0     0       0  ...     0       0     0     0      0
1      0        0        0     0       0  ...     0       0     0     0      0
2      0        0        0     0       0  ...     0       0     0     0      0
3      0        0        0     0       1  ...     0       0     0     0      0
4      0        0        0     0       0  ...     0       0     0     0      0

[5 rows x 5000 columns]

## Word Embedding using TF-IDF Vectorizer

In [15]:
# In TF-IDF vectorizer all the words do not have the same weightage unlike Part of Speech tagging 
# The most frequently appearing word (measured by Term Frequency (TF)) has the highest weightage
from sklearn. feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features = 5000)
Tfidf = tf.fit_transform(df['lemma2']).toarray()

In [16]:
pd.DataFrame(Tfidf, columns = cv.get_feature_names()).head()

aaron  abandon  ability  able    aboard  ...  zeta  zombie  zone  zoom  zwick
0    0.0      0.0      0.0   0.0  0.000000  ...   0.0     0.0   0.0   0.0    0.0
1    0.0      0.0      0.0   0.0  0.000000  ...   0.0     0.0   0.0   0.0    0.0
2    0.0      0.0      0.0   0.0  0.000000  ...   0.0     0.0   0.0   0.0    0.0
3    0.0      0.0      0.0   0.0  0.036018  ...   0.0     0.0   0.0   0.0    0.0
4    0.0      0.0      0.0   0.0  0.000000  ...   0.0     0.0   0.0   0.0    0.0

[5 rows x 5000 columns]

## Model Preprocessing (Encoding categorical variables and train test split)

In [17]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
df['class2'] = Encoder.fit_transform(df['class'])

## Model Training and Evaluation

Preparing two separate datasets for training for both the word embedding techniques

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
# Bag of Words (Count Vectorizer)
Train_X, Test_X, Train_Y, Test_Y = train_test_split(BOW, df['class2'], test_size = 0.2)

In [20]:
# TF-IDF Vectorizer
Train_X1, Test_X1, Train_Y1, Test_Y1 = train_test_split(Tfidf, df['class2'], test_size = 0.2)

### Naive Bayes (BOW)

In [46]:
from sklearn import model_selection, naive_bayes, svm, linear_model
from sklearn.metrics import accuracy_score
# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X,Train_Y)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",round(accuracy_score(predictions_NB, Test_Y)*100,2),"%")

Naive Bayes Accuracy Score ->  83.25 %


In [22]:
from sklearn import metrics
print(" ------ Confusion Matrix-----[TN FP  FN TP]")

print(metrics.confusion_matrix(predictions_NB, Test_Y))
print(metrics.classification_report(predictions_NB, Test_Y))

 ------ Confusion Matrix-----[TN FP  FN TP]
[[167  38]
 [ 29 166]]
              precision    recall  f1-score   support

           0       0.85      0.81      0.83       205
           1       0.81      0.85      0.83       195

    accuracy                           0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400



## Naive Bayes (TF_IDF)

In [23]:
Naive_1 = naive_bayes.MultinomialNB()
Naive_1.fit(Train_X1,Train_Y1)
# predict the labels on validation dataset
predictions_NB_1 = Naive.predict(Test_X1)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",round(accuracy_score(predictions_NB_1, Test_Y1)*100,2),"%")

Naive Bayes Accuracy Score ->  87.25 %


In [24]:
print(" ------ Confusion Matrix-----[TN FP  FN TP]")

print(metrics.confusion_matrix(predictions_NB_1, Test_Y1))
print(metrics.classification_report(predictions_NB_1, Test_Y1))

 ------ Confusion Matrix-----[TN FP  FN TP]
[[160  30]
 [ 21 189]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86       190
           1       0.86      0.90      0.88       210

    accuracy                           0.87       400
   macro avg       0.87      0.87      0.87       400
weighted avg       0.87      0.87      0.87       400



### Logistic Regression (BOW)

In [48]:
LR = linear_model.LogisticRegression(max_iter=300, random_state = 100)
LR.fit(Train_X, Train_Y)
predictions_LR = LR.predict(Test_X)

print("LR Accuracy Score -> ",round(accuracy_score(predictions_LR, Test_Y)*100,2),"%")

LR Accuracy Score ->  84.5 %


In [49]:
confusion_matrix(predictions_LR, Test_Y)

array([[166,  32],
       [ 30, 172]])

In [50]:
print(classification_report(predictions_LR, Test_Y))

              precision    recall  f1-score   support

           0       0.85      0.84      0.84       198
           1       0.84      0.85      0.85       202

    accuracy                           0.84       400
   macro avg       0.85      0.84      0.84       400
weighted avg       0.85      0.84      0.84       400



### Logistic Regression (TF_IDF)

In [51]:
LR_1 = linear_model.LogisticRegression(max_iter=300, random_state = 100)
LR_1.fit(Train_X1, Train_Y1)
predictions_LR_1 = LR_1.predict(Test_X1)

print("LR Accuracy Score -> ",round(accuracy_score(predictions_LR_1, Test_Y1)*100,2),"%")

LR Accuracy Score ->  81.5 %


In [52]:
confusion_matrix(predictions_LR_1, Test_Y1)

array([[145,  38],
       [ 36, 181]])

In [53]:
print(classification_report(predictions_LR_1, Test_Y1))

              precision    recall  f1-score   support

           0       0.80      0.79      0.80       183
           1       0.83      0.83      0.83       217

    accuracy                           0.81       400
   macro avg       0.81      0.81      0.81       400
weighted avg       0.81      0.81      0.81       400



### Support Vector Machines (BOW)

In [25]:
SVM = svm.SVC(C = 1.0, kernel='linear', degree = 3, gamma = 'auto')
SVM.fit(Train_X, Train_Y)
predictions_SVM = SVM.predict(Test_X)

print("SVM Accuracy Score -> ",round(accuracy_score(predictions_SVM, Test_Y)*100,2),"%")

SVM Accuracy Score ->  83.5 %


In [37]:
confusion_matrix(predictions_SVM, Test_Y)

array([[165,  35],
       [ 31, 169]])

In [40]:
print(classification_report(predictions_SVM, Test_Y))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       200
           1       0.83      0.84      0.84       200

    accuracy                           0.83       400
   macro avg       0.84      0.83      0.83       400
weighted avg       0.84      0.83      0.83       400



### Support Vector Machines (TF-IDF)

In [26]:
SVM_1 = svm.SVC(C = 1.0, kernel='linear', degree = 3, gamma = 'auto')
SVM_1.fit(Train_X1, Train_Y1)
predictions_SVM_1 = SVM_1.predict(Test_X1)

print("SVM Accuracy Score -> ",round(accuracy_score(predictions_SVM_1, Test_Y1)*100,2),"%")

SVM Accuracy Score ->  80.5 %


In [42]:
confusion_matrix(predictions_SVM_1, Test_Y1)

array([[140,  37],
       [ 41, 182]])

In [45]:
print(classification_report(predictions_SVM_1, Test_Y1))

              precision    recall  f1-score   support

           0       0.77      0.79      0.78       177
           1       0.83      0.82      0.82       223

    accuracy                           0.81       400
   macro avg       0.80      0.80      0.80       400
weighted avg       0.81      0.81      0.81       400

